version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo 'Running eslint THEN unit tests'
      - cd hello-world
      - echo pwd
      - echo ls
      - npm run lint
